### PR TITLE
ECO-499 Adding unit testing to CI

### PR DESCRIPTION
**Pull request by sacherjj**
Updating .drone.yml to add unit testing.

### CODE REVIEW

**Comment by sacherjj** [comment]
bors try

**Comment by sacherjj** [comment]
bors try-

**Comment by sacherjj** [comment]
bors try

**Comment by sacherjj** [comment]
bors try

**Comment by TomVasile** [comment]
bors try-

**Comment by TomVasile** [comment]
bors try

**Comment by TomVasile** [comment]
bors try-

**Comment by sacherjj** [comment]
bors try

**Comment by sacherjj** [comment]
bors try

**Comment by sacherjj** [comment]
bors try

**Comment by sacherjj** [comment]
bors try

**Comment by sacherjj** [comment]
bors try

**Comment by sacherjj** [comment]
Ready to go once I get Python 3.8 in buildenv.

**Comment by sacherjj** [comment]
bors try

**Comment by sacherjj** [comment]
bors try

**Pull request merged**
