### PR TITLE
NO-TICK Shortening bors timeout to 30 minutes.

### PR DESCRIPTION
**Pull request by sacherjj**
Shortening the bors timeout to 30 minutes from 3 hours and testing drone security fixes with this merge.

### CODE REVIEW

**Comment by sacherjj** [comment]
bors try

**Comment by sacherjj** [comment]
bors -try

**Comment by sacherjj** [comment]
bors try

**Comment by sacherjj** [comment]
bors -try

**Review by piotr-putit — APPROVED** [review]

**Pull request merged**
